### PR TITLE
Commenting out code to print auth tokens

### PR DESCRIPTION
**Pull request by ykosaraju**
*Issue #, if available:*
N/A

*Description of changes:*
Commenting out the line which prints the auth token, which will prevent auth tokens to be logged in Cloudwatch

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by plygrnd** [comment]
This needs to be fixed for [Go](https://github.com/awslabs/aws-apigateway-lambda-authorizer-blueprints/blob/master/blueprints/go/main.go#L26) and [NodeJS](https://github.com/awslabs/aws-apigateway-lambda-authorizer-blueprints/blob/master/blueprints/nodejs/index.js#L13), too.

**Comment by plygrnd** [comment]
diff --git a/blueprints/go/main.go b/blueprints/go/main.go
index fc378c9..6849388 100644
--- a/blueprints/go/main.go
+++ b/blueprints/go/main.go
@@ -23,7 +23,9 @@ import (
 )
 
 func handleRequest(ctx context.Context, event events.APIGatewayCustomAuthorizerRequest) (events.APIGatewayCustomAuthorizerResponse, error) {
-	log.Println("Client token: " + event.AuthorizationToken)
+	// We shouldn't print the auth token
+	// unless absolutely necessary
+	// log.Println("Client token: " + event.AuthorizationToken)
 	log.Println("Method ARN: " + event.MethodArn)
 
 	// validate the incoming token
diff --git a/blueprints/nodejs/index.js b/blueprints/nodejs/index.js
index 087eb8f..71cab5e 100644
--- a/blueprints/nodejs/index.js
+++ b/blueprints/nodejs/index.js
@@ -10,7 +10,9 @@
 console.log('Loading function');
 
 exports.handler = function(event, context, callback) {
-    console.log('Client token: ' + event.authorizationToken);
+  	   // We shouldn't print the auth token
+	  // unless absolutely necessary
+    // console.log('Client token: ' + event.authorizationToken);
     console.log('Method ARN: ' + event.methodArn);
 
     // validate the incoming token

**Comment by ykosaraju** [comment]
Thanks @plygrnd 
Added those to the PR

**Comment by plygrnd** [comment]
@jackrk update?

**Pull request merged**
